// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommitInput struct {
	RefHeadID string `json:"refHeadId"`
	Row       int    `json:"row"`
	Col       int    `json:"col"`
	Val       int    `json:"val"`
}
